### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [jetgogol/ttl.lua#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

I see a user matching your username wrote [MIT on the FSD](https://directory.fsf.org/wiki?title=Ttl.lua&oldid=89459#tab=Details), but I do not see the MIT license here.

**Comment by jetgogol** [comment]
Thanks for issue! Changed my opinion for license and now it should be GPL v3
